# Site settings
title: Seshadri Kolluri
email: Seshadri.Kolluri@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seshadri.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
mathjax: true

theme: jekyll-theme-cayman